### PR TITLE
fixed misspelling

### PR DESCRIPTION
**Pull request by dhinakg**

### CODE REVIEW

**Comment by 1byte2bytes** [comment]
Thanks for the pull request, will merge if the test returns successful. It should since it's just a README change. Hang tight!

**Comment by dhinakg** [comment]
Really weird though, Travis CI didn't finish yet?

**Comment by 1byte2bytes** [comment]
screen shot 2017-04-11 at 11 14 20 am

You can track the status using the panel above the new comment box or [here](https://travis-ci.org/StarbotDiscord/BuildScript/builds/221052698)

**Comment by dhinakg** [comment]
Yeah I know, just that after 20 minutes the build still didn't start.

**Comment by 1byte2bytes** [comment]
Travis-CI can be slow to start macOS builds due to the relatively low count of build environments and it's somewhat beta-ness. I have expanded the testing to include Linux after this pull request. I have merged the request anyway, since the build is broken anyway.

**Comment by dhinakg** [comment]
Ahh.

**Pull request merged**
